# Generated by Django 4.1.7 on 2023-04-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo_equipo', models.CharField(max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_puesta_marcha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravedad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_referencia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=20)),
                ('detalles', models.CharField(max_length=500)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_resolucion', models.DateTimeField()),
                ('comentarios_ticket', models.CharField(max_length=500)),
                ('empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.empleado')),
                ('equipo_a_reparar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.equipo')),
                ('estado_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.estado_ticket')),
                ('tipo_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.tipo_ticket')),
                ('urgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.urgencia')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.planta'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reto1.proveedor'),
        ),
    ]
